--tells Snowflake how to read the CSV
CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_STANDARD
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
;

--staging AWS credentials
CREATE STAGE IF NOT EXISTS RAW.S3_TRIBUTARY_RAW
  URL = 's3://first-test-tributary-nrudiger/raw/'
  CREDENTIALS = (AWS_KEY_ID='REDACTED' AWS_SECRET_KEY='REDACTED')
  FILE_FORMAT = RAW.CSV_STANDARD
;

--Raw table of data
  CREATE TABLE IF NOT EXISTS RAW.SUPERSTORE_ORDERS (
  ROW_ID VARCHAR, ORDER_ID VARCHAR, ORDER_DATE VARCHAR, SHIP_DATE VARCHAR,
  SHIP_MODE VARCHAR, CUSTOMER_ID VARCHAR, CUSTOMER_NAME VARCHAR, SEGMENT VARCHAR,
  COUNTRY VARCHAR, CITY VARCHAR, STATE VARCHAR, POSTAL_CODE VARCHAR, REGION VARCHAR,
  PRODUCT_ID VARCHAR, CATEGORY VARCHAR, SUB_CATEGORY VARCHAR, PRODUCT_NAME VARCHAR,
  SALES VARCHAR, QUANTITY VARCHAR, DISCOUNT VARCHAR, PROFIT VARCHAR
);

--Load data
COPY INTO RAW.SUPERSTORE_ORDERS
  FROM @RAW.S3_TRIBUTARY_RAW/2026-09-09/
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_STANDARD)
  ON_ERROR = 'ABORT_STATEMENT'
;


--verify count and data quality
SELECT COUNT(*) FROM RAW.SUPERSTORE_ORDERS;
SELECT * FROM RAW.SUPERSTORE_ORDERS LIMIT 10
;
