CREATE WAREHOUSE IF NOT EXISTS TRIBUTARY_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS TRIBUTARY;

CREATE SCHEMA IF NOT EXISTS TRIBUTARY.RAW;